# Generated by Django 3.1.7 on 2022-04-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220425_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
