# Generated by Django 3.1.7 on 2022-04-26 14:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pedido_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('valor_total_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3)),
                ('valor_total', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(100000)])),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.formapagamento')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('qtd', models.IntegerField(default=1)),
                ('valor_total_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3)),
                ('valor_total', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(100000)])),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orcamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
